language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

stages:
  - Test
  - Code style & static analysis

before_install:
  - if [[ $TRAVIS_PHP_VERSION != '7.4snapshot' ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer update --no-interaction --no-suggest --prefer-dist

script: 
  - vendor/bin/phpunit


jobs:
  include:
    - name: Code coverage
      php: 7.3
      script:
        - vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml
      after_success:
        - php bin/php-coveralls -v
    - stage: Code style & static analysis
      name: PHP CS Fixer
      script: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - name: PHPStan
      script: vendor/bin/phpstan analyze
