language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - Test
  - Code style & static analysis

before_install:
  - if [ "$SYMFONY_REQUIRE" != "" ]; then composer global require symfony/flex; fi

install:
  - composer update --no-interaction --no-suggest --prefer-dist --prefer-stable

script: 
  - vendor/bin/phpunit

jobs:
  include:
    - name: Prefer lowest
      php: 7.1
      env:
        SYMFONY_DEPRECATIONS_HELPER: disabled
      install:
        - composer update --prefer-lowest --no-interaction --no-suggest --prefer-dist --prefer-stable
    - php: 7.1
      env:
        SYMFONY_REQUIRE: 3.4
        SYMFONY_DEPRECATIONS_HELPER: disabled
    - env:
        SYMFONY_REQUIRE: 4.4
    - env:
        SYMFONY_REQUIRE: 5
    - stage: Code style & static analysis
      name: PHP CS Fixer
      script: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - name: PHPStan
      script: vendor/bin/phpstan analyze
