language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

stages:
  - Test
  - Code style & static analysis

before_install:
  - phpenv config-rm xdebug.ini || echo "Unable to remove xDebug"
  - if [[ $TRAVIS_PHP_VERSION != '7.1' ]]; then export SYMFONY_DEPRECATIONS_HELPER=disabled; fi

install:
  - composer update --no-interaction --no-suggest --prefer-dist --prefer-stable

script: 
  - vendor/bin/phpunit

jobs:
  include:
    - name: Prefer lowest
      php: 7.1
      env:
        SYMFONY_DEPRECATIONS_HELPER: disabled
      install:
        - composer update --prefer-lowest --no-interaction --no-suggest --prefer-dist --prefer-stable
    - name: Code coverage
      php: 7.3
      before_install: []
      script:
        - vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml
      after_success:
        - vendor/bin/php-coveralls -v
    - stage: Code style & static analysis
      name: PHP CS Fixer
      script: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - name: PHPStan
      script: vendor/bin/phpstan analyze
