name: CI

on:
  pull_request: null
  push:
    branches:
      - 1.x

jobs:
  Tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        php:
          - '7.4'
          - '7.3'
          - '7.2'
        composer_option: ['']
        experimental: [false]
        include:
#          - description: 'nightly'
#            os: 'ubuntu-latest'
#            php: '8.0'
          - description: 'Symfony 3.4'
            os: 'ubuntu-latest'
            php: '7.2'
            symfony_require: '^3.4'
            deprecations: 'disabled'
          - description: 'Symfony 4.4'
            os: 'ubuntu-latest'
            php: '7.4'
            symfony_require: '^4.4'
          - description: 'Symfony 5'
            os: 'ubuntu-latest'
            php: '7.4'
            symfony_require: '^5'
          - description: '--prefer lowest'
            os: 'ubuntu-latest'
            php: '7.2'
            composer_option: '--prefer-lowest'
            deprecations: 'disabled'

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ matrix.php }}${{ matrix.composer_option }} 
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer global require symfony/flex
        if: matrix.symfony_require
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony_require }}
      - run: composer update --no-progress --ansi ${{ matrix.composer_option }}
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: '7.4'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-progress --ansi
      - run: vendor/bin/php-cs-fixer fix --ansi --verbose --dry-run
  PHPStan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: '7.4'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-progress --ansi
      - run: vendor/bin/phpstan analyse
